language: bash

git:
  depth: false

services:
  - docker

script:
  - git checkout master
  - docker run -it --rm -v $PWD:/app -e WEBPACK_MODE=production -w /app node:alpine sh -c 'npm install && npm run webpack && (echo "app.vigilo.city" > /app/dist/CNAME) && mv /app/dist /app/public'
  - git checkout -- .
  - git checkout develop
  - docker run -it --rm -v $PWD:/app -e WEBPACK_MODE=production -w /app node:alpine sh -c 'npm install && npm run webpack && (echo "app.vigilo.city" > /app/dist/CNAME) && mv /app/dist /app/public/develop'
  - find public

deploy:
  local_dir: public
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|develop$