import L from 'leaflet';
import i18next from 'i18next';
import dataManager from './dataManager';
import { addBaseLayers } from './map-layers';
import { escapeHtml } from './utils';

// Observations closer than this are shown around the current one
const NEARBY_RADIUS_M = 500;

var minimap;

/**
 * Small map in the observation detail: the observation itself, a 500 m circle and
 * the (currently filtered) observations within that radius. Replaces the static
 * image generated by the backend (maps/<token>_zoom.jpg), often missing.
 */
export async function showIssueMiniMap(container, caption, issue) {
	if (minimap !== undefined) {
		minimap.remove();
		minimap = undefined;
	}
	if (!container) {
		return;
	}
	var center = L.latLng(issue.lat_float, issue.lon_float);
	var map = minimap = L.map(container, { scrollWheelZoom: false });
	addBaseLayers(map, { control: false });
	map.fitBounds(center.toBounds(NEARBY_RADIUS_M * 2));

	L.circle(center, {
		radius: NEARBY_RADIUS_M,
		color: '#1f2328',
		weight: 1,
		dashArray: '4 4',
		fill: false,
		interactive: false
	}).addTo(map);

	var issues = await dataManager.getData();
	if (map !== minimap) {
		// another observation was opened meanwhile
		return;
	}
	var nearby = issues.filter((i) => i.token != issue.token && center.distanceTo([i.lat_float, i.lon_float]) <= NEARBY_RADIUS_M);
	nearby.forEach((i) => {
		L.circleMarker([i.lat_float, i.lon_float], {
			radius: 7,
			color: '#ffffff',
			weight: 2,
			fillColor: i.color,
			fillOpacity: 0.9
		})
			.bindTooltip(escapeHtml(i18next.t("category-name-" + i.categorie)) + '<br>' + escapeHtml(i.address))
			.on('click', () => window.viewIssue(i.token))
			.addTo(map);
	});
	// the observation itself, on top
	L.marker(center, { title: i18next.t("see-on-map") })
		.on('click', () => window.centerOnIssue(issue.token))
		.addTo(map);

	if (caption) {
		caption.textContent = nearby.length == 0
			? i18next.t("nearby-none")
			: i18next.t(nearby.length == 1 ? "nearby-one" : "nearby-other", { count: nearby.length });
	}
}

/** Recompute the map size once the detail window has finished opening */
export function refreshIssueMiniMap() {
	if (minimap !== undefined) {
		minimap.invalidateSize();
	}
}
