// import main CSS
import '../css/main.scss';

import $ from 'jquery';
window.$ = $;



// Fix import leaflet with webpack https://github.com/PaulLeCam/react-leaflet/issues/255
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
	iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
	iconUrl: require('leaflet/dist/images/marker-icon.png'),
	shadowUrl: require('leaflet/dist/images/marker-shadow.png'),
});




window.WE_ARE_ON_A_MOBILE = typeof orientation !== 'undefined' || navigator.userAgent.toLowerCase().indexOf('mobile') >= 0 || window.location.search.indexOf('mobile') >=0;

// Observation photos: if the original photo can't be loaded (e.g. refused by the
// backend), show the panel generated by the backend instead; if there is no photo at all
// (404 PHOTONOTFOUND), or the instance can't be reached, a default image
const PHOTO_MISSING = require('../img/photo-missing.svg');
document.addEventListener('error', (e) => {
	var img = e.target;
	if (!img || img.tagName != 'IMG' || img.dataset.photoMissing !== undefined) {
		return;
	}
	if (img.dataset.fallback && img.getAttribute('src') != img.dataset.fallback) {
		img.src = img.dataset.fallback;
	} else if (img.dataset.fallback !== undefined || img.classList.contains('issue-photo')) {
		img.dataset.photoMissing = '';
		img.classList.add('photo-missing');
		img.src = PHOTO_MISSING;
	}
}, true);

// registers the install prompt listener before the app is initialized
import './install';
import { hideSplash } from './splash';
import VigiloApp from './app';
window.vigilo = new VigiloApp();
// the loading screen goes away when the app is ready, or if it fails to start
window.vigilo.init().catch((e) => console.error(e)).finally(hideSplash);
